#!/usr/bin/python

import sys
import getopt
from datetime import timedelta


def main(argv):
    inputfile = ''

    try:
        opts, args = getopt.getopt(argv, "hi:o:", ["ifile="])
    except getopt.GetoptError:
        print
        'transform-ctm2srt.py -i <inputfile>'
        sys.exit(2)
    for opt, arg in opts:
        if opt == '-h':
            print
            'transform-ctm2srt.py -i <inputfile>'
            sys.exit()
        elif opt in ("-i", "--ifile"):
            inputfile = arg
    print('Input file is ', inputfile)
    outputfile = inputfile.split('.')[0] + '.srt'
    print('Output file is ', outputfile)
    of = open(outputfile, "w")

    with open(inputfile) as fp:
        line = fp.readline()
        cnt = 1
        previous_timestamp = 0.01
        previous_line = 'Subtitles generated by Kaldi NL'
        while line:
            line_strip_split = line.strip().split('. ')
            str_tc_new = line_strip_split[1].split(' ')[1].replace(')', '')
            td_old = timedelta(seconds=previous_timestamp)
            td_new = timedelta(seconds=float(str_tc_new))

            of.write(str(cnt) + '\n')
            of.write('0' + str(td_old).replace('.', ',').replace('0000', '0') + ' --> ' + '0' + str(td_new).replace('.', ',').replace('0000', '0') + '\n')
            of.write(previous_line + '. \n \n')

            previous_timestamp = float(str_tc_new)
            previous_line = line_strip_split[0]
            line = fp.readline()
            cnt += 1

    # Finally write last line
    td_final = timedelta(seconds=previous_timestamp+5.00)
    of.write(str(cnt) + '\n')
    of.write('0' + str(td_new).replace('.', ',').replace('0000', '0') + ' --> ' + '0' + str(td_final).replace('.', ',').replace('0000', '0') + '\n')
    of.write(previous_line + '. \n \n')
    of.close()


if __name__ == "__main__":
    main(sys.argv[1:])
